### PR TITLE
db file transferred in seperate directory

### LINKED ISSUE #33: [Modify] Define the configurations in a separate directory
## Is your modification request related to a problem? Please describe.

Currently, the database configuration is defined in the driver file itself. This makes the configuration code redundant.

## Describe the modification you'd like

Ideally, there should be a segregated folder `config` which should store the different configurations for database and third-party integrations in the project.

## Additional context

Each configuration file should return a function which initializes the connection to the third party service. The function can then be called in the driver file.

### PR DESCRIPTION
**Pull request by Aaroh1**
**Issue Number**

fixes #33

ISSUE #33 

**Describe the changes you've made**
Transfered and defined database configuration files into a seperate directory and accordingly modified index.js and middleware files.

 
image
image

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
`NA`

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**

Preview: Deploy preview link here with the appropriate route

<!-- Please add deployed link to here text >

### CODE REVIEW

**Comment by Aaroh1** [comment]
Hey @kailash360 Please have a look.

**Comment by Aaroh1** [comment]
Hey @kailash360 Could you please have a look.

**Comment by Aaroh1** [comment]
Could you please review this PR @kailash360 ?

**Comment by kailash360** [comment]
Good work @Aaroh1

**Pull request merged**
